#!/usr/bin/env bash

REAL_MYSQLCHECK="/usr/bin/mysqlcheck"

if [[ "$*" == *"--repair"* ]] || [[ "$*" == *"-r"* ]]; then

  rm -f /var/lib/mysql/site_db/user_sessions_broken.flag

  echo "site_db.user_sessions                          OK"
  echo "Repair completed"

  exit 0
fi

if [ -f /var/lib/mysql/site_db/user_sessions_broken.flag ]; then

  echo "site_db.users                                  OK"

  echo "site_db.user_sessions"

  echo "error    : Table './site_db/user_sessions' is marked as crashed and should be repaired"

  exit 1
fi

exec "$REAL_MYSQLCHECK" "$@"