services:
  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  web:
    env_file:
      - .env

    environment:
      DEBUG: "True"

    ports:
      - "8000:8000"

  worker:
    env_file:
      - .env
    environment:
      DEBUG: "True"

  gateway:
    ports:
      - "8081:80"

volumes:
  postgres_data:
    external: true
    name: ticket-sandbox_postgres_data