# Generated by Django 6.0.5 on 2026-08-05 10:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0003_seed_l1_taxonomy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Название видно наставнику, но не показывается сотруднику.",
                        max_length=180,
                        verbose_name="Внутреннее название",
                    ),
                ),
                ("slug", models.SlugField(max_length=120, verbose_name="Slug")),
                (
                    "level",
                    models.CharField(
                        choices=[("l1", "L1"), ("l2", "L2"), ("prime", "Prime")],
                        max_length=16,
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("medium", "Средняя"),
                            ("hard", "Сложная"),
                            ("advanced", "Повышенная"),
                        ],
                        default="hard",
                        max_length=16,
                        verbose_name="Сложность",
                    ),
                ),
                (
                    "scenario",
                    models.TextField(
                        blank=True,
                        help_text="Описание проблемы или обращения, которое увидит сотрудник.",
                        verbose_name="Ситуация и вводные",
                    ),
                ),
                (
                    "diagnostic_data",
                    models.TextField(
                        blank=True,
                        help_text="Необязательный блок с логами, конфигурацией или выводом команд.",
                        verbose_name="Логи и вывод команд",
                    ),
                ),
                ("prompt", models.TextField(verbose_name="Вопрос")),
                (
                    "answer_type",
                    models.CharField(
                        choices=[
                            ("single_choice", "Один правильный ответ"),
                            ("multiple_choice", "Несколько правильных ответов"),
                        ],
                        default="single_choice",
                        max_length=32,
                        verbose_name="Тип ответа",
                    ),
                ),
                (
                    "time_limit_seconds",
                    models.PositiveSmallIntegerField(
                        default=90,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(300),
                        ],
                        verbose_name="Время на ответ, секунд",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Почему ответ правильный и какое знание проверяет вопрос.",
                        verbose_name="Объяснение для наставника",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("active", "Активен"),
                            ("archived", "Архив"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="assessment.questionfamily",
                        verbose_name="Семейство вопросов",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
                "ordering": (
                    "family__skill__topic__order",
                    "family__skill__order",
                    "family__order",
                    "order",
                    "title",
                ),
            },
        ),
        migrations.CreateModel(
            name="AnswerOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Вариант ответа")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Правильный ответ"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_options",
                        to="assessment.question",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответов",
                "ordering": ("order", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("family", "slug"),
                name="assessment_unique_question_slug_per_family",
            ),
        ),
    ]
