# Generated by Django 6.0.5 on 2026-08-06 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0004_question_answeroption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer_type",
            field=models.CharField(
                choices=[
                    ("single_choice", "Один правильный ответ"),
                    ("multiple_choice", "Несколько правильных ответов"),
                    ("matching", "Сопоставление"),
                    ("ordering", "Последовательность"),
                    ("line_selection", "Выбор строк"),
                ],
                default="single_choice",
                max_length=32,
                verbose_name="Тип ответа",
            ),
        ),
        migrations.CreateModel(
            name="MatchingPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("left_text", models.TextField(verbose_name="Левая часть")),
                (
                    "right_text",
                    models.TextField(verbose_name="Правильная правая часть"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching_pairs",
                        to="assessment.question",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пара для сопоставления",
                "verbose_name_plural": "Пары для сопоставления",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="OrderingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Элемент последовательности")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Чем меньше значение, тем раньше должен находиться элемент.",
                        verbose_name="Правильная позиция",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordering_items",
                        to="assessment.question",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент последовательности",
                "verbose_name_plural": "Элементы последовательности",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="SelectableLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Строка")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Нужно выбрать"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Номер строки"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selectable_lines",
                        to="assessment.question",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка лога или конфигурации",
                "verbose_name_plural": "Строки лога или конфигурации",
                "ordering": ("order", "id"),
            },
        ),
    ]
