# Generated by Django 6.0.5 on 2026-08-06 12:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessment",
            "0005_alter_question_answer_type_matchingpair_orderingitem_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamBlueprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="Slug"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("l1", "L1"), ("l2", "L2"), ("prime", "Prime")],
                        max_length=16,
                        verbose_name="Уровень сотрудников",
                    ),
                ),
                (
                    "pass_percentage",
                    models.PositiveSmallIntegerField(
                        default=85,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Проходной результат, %",
                    ),
                ),
                (
                    "allow_back_navigation",
                    models.BooleanField(
                        default=False,
                        help_text="Если выключено, после отправки ответа вернуться к вопросу нельзя.",
                        verbose_name="Разрешить возврат к вопросам",
                    ),
                ),
                (
                    "shuffle_questions",
                    models.BooleanField(
                        default=True, verbose_name="Перемешивать вопросы"
                    ),
                ),
                (
                    "shuffle_answer_options",
                    models.BooleanField(
                        default=True, verbose_name="Перемешивать варианты ответов"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
            ],
            options={
                "verbose_name": "Шаблон теста",
                "verbose_name_plural": "Шаблоны тестов",
                "ordering": ("level", "name"),
            },
        ),
        migrations.CreateModel(
            name="BlueprintTopicQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_count",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Количество вопросов",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blueprint_quotas",
                        to="assessment.topic",
                        verbose_name="Тематика",
                    ),
                ),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_quotas",
                        to="assessment.examblueprint",
                        verbose_name="Шаблон теста",
                    ),
                ),
            ],
            options={
                "verbose_name": "Квота тематики",
                "verbose_name_plural": "Квоты тематик",
                "ordering": ("order", "topic__order", "topic__name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("blueprint", "topic"),
                        name="assessment_unique_topic_per_blueprint",
                    )
                ],
            },
        ),
    ]
