# Generated by Django 6.0.5 on 2026-08-06 13:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0006_examblueprint_blueprinttopicquota"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlueprintSkillQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_count",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Количество вопросов",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Квота навыка",
                "verbose_name_plural": "Квоты навыков",
                "ordering": (
                    "order",
                    "skill__topic__order",
                    "skill__order",
                    "skill__name",
                ),
            },
        ),
        migrations.RemoveConstraint(
            model_name="blueprinttopicquota",
            name="assessment_unique_topic_per_blueprint",
        ),
        migrations.AddField(
            model_name="blueprintskillquota",
            name="blueprint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill_quotas",
                to="assessment.examblueprint",
                verbose_name="Шаблон теста",
            ),
        ),
        migrations.AddField(
            model_name="blueprintskillquota",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="blueprint_quotas",
                to="assessment.skill",
                verbose_name="Проверяемый навык",
            ),
        ),
        migrations.RemoveField(
            model_name="blueprinttopicquota",
            name="blueprint",
        ),
        migrations.RemoveField(
            model_name="blueprinttopicquota",
            name="topic",
        ),
        migrations.AddConstraint(
            model_name="blueprintskillquota",
            constraint=models.UniqueConstraint(
                fields=("blueprint", "skill"),
                name="assessment_unique_skill_per_blueprint",
            ),
        ),
        migrations.DeleteModel(
            name="BlueprintTopicQuota",
        ),
    ]
