# Generated by Django 6.0.5 on 2026-08-07 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0009_assessmentcampaign_examassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveSmallIntegerField(verbose_name="Номер попытки"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "В процессе"),
                            ("completed", "Завершена"),
                            ("invalidated", "Аннулирована"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "selection_seed",
                    models.CharField(
                        max_length=64, verbose_name="Seed выбора вопросов"
                    ),
                ),
                (
                    "campaign_name",
                    models.CharField(max_length=180, verbose_name="Название кампании"),
                ),
                (
                    "blueprint_name",
                    models.CharField(max_length=150, verbose_name="Название шаблона"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("l1", "L1"), ("l2", "L2"), ("prime", "Prime")],
                        max_length=16,
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "pass_percentage",
                    models.PositiveSmallIntegerField(
                        verbose_name="Проходной результат, %"
                    ),
                ),
                (
                    "allow_back_navigation",
                    models.BooleanField(verbose_name="Разрешён возврат к вопросам"),
                ),
                (
                    "shuffle_questions",
                    models.BooleanField(verbose_name="Вопросы перемешаны"),
                ),
                (
                    "shuffle_answer_options",
                    models.BooleanField(verbose_name="Варианты ответов перемешаны"),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Начата"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершена"
                    ),
                ),
                (
                    "invalidated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Аннулирована"
                    ),
                ),
                (
                    "invalidation_reason",
                    models.TextField(blank=True, verbose_name="Причина аннулирования"),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="assessment.examassignment",
                        verbose_name="Назначение",
                    ),
                ),
                (
                    "invalidated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invalidated_exam_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Аннулировал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка теста",
                "verbose_name_plural": "Попытки тестов",
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="ExamQuestionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(verbose_name="Позиция в тесте"),
                ),
                (
                    "topic_name",
                    models.CharField(max_length=100, verbose_name="Тематика"),
                ),
                ("topic_slug", models.SlugField(max_length=100)),
                ("skill_name", models.CharField(max_length=150, verbose_name="Навык")),
                ("skill_slug", models.SlugField(max_length=100)),
                (
                    "family_name",
                    models.CharField(max_length=150, verbose_name="Семейство"),
                ),
                ("family_slug", models.SlugField(max_length=100)),
                (
                    "question_title",
                    models.CharField(
                        max_length=180, verbose_name="Внутреннее название вопроса"
                    ),
                ),
                ("question_slug", models.SlugField(max_length=120)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single_choice", "Один правильный ответ"),
                            ("multiple_choice", "Несколько правильных ответов"),
                            ("matching", "Сопоставление"),
                            ("ordering", "Последовательность"),
                            ("line_selection", "Выбор строк"),
                        ],
                        max_length=32,
                        verbose_name="Тип вопроса",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("medium", "Средняя"),
                            ("hard", "Сложная"),
                            ("advanced", "Повышенная"),
                        ],
                        max_length=16,
                        verbose_name="Сложность",
                    ),
                ),
                ("scenario", models.TextField(blank=True, verbose_name="Ситуация")),
                (
                    "diagnostic_data",
                    models.TextField(blank=True, verbose_name="Логи и данные"),
                ),
                ("prompt", models.TextField(verbose_name="Вопрос")),
                (
                    "time_limit_seconds",
                    models.PositiveSmallIntegerField(verbose_name="Время на ответ"),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, verbose_name="Объяснение для наставника"
                    ),
                ),
                (
                    "visible_payload",
                    models.JSONField(
                        default=dict, verbose_name="Данные для показа сотруднику"
                    ),
                ),
                (
                    "grading_payload",
                    models.JSONField(
                        default=dict, verbose_name="Данные для проверки ответа"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_snapshots",
                        to="assessment.examattempt",
                        verbose_name="Попытка",
                    ),
                ),
                (
                    "source_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_snapshots",
                        to="assessment.question",
                        verbose_name="Исходный вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Снимок вопроса",
                "verbose_name_plural": "Снимки вопросов",
                "ordering": ("position",),
            },
        ),
        migrations.AddConstraint(
            model_name="examattempt",
            constraint=models.UniqueConstraint(
                fields=("assignment", "attempt_number"),
                name="assessment_unique_attempt_number_per_assignment",
            ),
        ),
        migrations.AddConstraint(
            model_name="examquestionsnapshot",
            constraint=models.UniqueConstraint(
                fields=("attempt", "position"),
                name="assessment_unique_question_position_per_attempt",
            ),
        ),
    ]
