# Generated by Django 6.0.5 on 2026-08-07 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0010_examattempt_examquestionsnapshot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response_payload",
                    models.JSONField(default=dict, verbose_name="Ответ сотрудника"),
                ),
                (
                    "score_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Результат, %",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False, verbose_name="Полностью правильный"
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Отвечен"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer",
                        to="assessment.examquestionsnapshot",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на вопрос",
                "verbose_name_plural": "Ответы на вопросы",
                "ordering": ("snapshot__position",),
            },
        ),
    ]
