# Generated by Django 6.0.5 on 2026-08-07 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0011_examanswer"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Итоговый результат, %",
                    ),
                ),
                ("passed", models.BooleanField(verbose_name="Порог пройден")),
                (
                    "total_questions",
                    models.PositiveSmallIntegerField(verbose_name="Всего вопросов"),
                ),
                (
                    "fully_correct_questions",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Полностью правильных ответов"
                    ),
                ),
                (
                    "topic_breakdown",
                    models.JSONField(default=dict, verbose_name="Результаты по темам"),
                ),
                (
                    "skill_breakdown",
                    models.JSONField(
                        default=dict, verbose_name="Результаты по навыкам"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="assessment.examattempt",
                        verbose_name="Попытка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат тестирования",
                "verbose_name_plural": "Результаты тестирования",
            },
        ),
    ]
