# Generated by Django 6.0.5 on 2026-08-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0012_assessmentresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="examanswer",
            name="response_time_seconds",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Время ответа, секунд"
            ),
        ),
        migrations.AddField(
            model_name="examanswer",
            name="timed_out",
            field=models.BooleanField(default=False, verbose_name="Время истекло"),
        ),
        migrations.AddField(
            model_name="examquestionsnapshot",
            name="started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Вопрос открыт"
            ),
        ),
    ]
