# Generated by Django 6.0.5 on 2026-08-21 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0014_replace_cron_with_control_panels"),
    ]

    operations = [
        migrations.AddField(
            model_name="examquestionsnapshot",
            name="diagnostic_blocks",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="QuestionDiagnosticBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[("text", "Текст"), ("code", "Код / лог")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnostic_blocks",
                        to="assessment.question",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
    ]
