# Generated by Django 6.0.5 on 2026-05-15 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Доступно"),
                            ("in_progress", "В работе"),
                            ("passed", "Пройдено"),
                            ("failed", "Не пройдено"),
                        ],
                        default="available",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "attempts_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество проверок"
                    ),
                ),
                (
                    "restart_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество перезапусков"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Начато"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершено"
                    ),
                ),
                (
                    "last_check_output",
                    models.TextField(blank=True, verbose_name="Лог проверки"),
                ),
                (
                    "trainee_report",
                    models.TextField(blank=True, verbose_name="Отчет стажера"),
                ),
                (
                    "client_answer",
                    models.TextField(blank=True, verbose_name="Ответ клиенту"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sandbox.task",
                        verbose_name="Задание",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Стажер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка прохождения",
                "verbose_name_plural": "Попытки прохождения",
                "unique_together": {("user", "task")},
            },
        ),
    ]
