# Generated by Django 6.0.5 on 2026-05-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0002_taskattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattempt",
            name="container_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ID контейнера"
            ),
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="container_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Имя контейнера"
            ),
        ),
    ]
