# Generated by Django 6.0.5 on 2026-05-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0003_taskattempt_container_id_taskattempt_container_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattempt",
            name="shell_command",
            field=models.TextField(blank=True, verbose_name="Команда подключения"),
        ),
    ]
