# Generated by Django 6.0.5 on 2026-05-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0004_taskattempt_shell_command"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("in_progress", "В работе"),
                    ("on_review", "На проверке"),
                    ("failed", "Доработать"),
                    ("passed", "Пройдено"),
                ],
                default="new",
                max_length=32,
                verbose_name="Статус",
            ),
        ),
    ]
