# Generated by Django 6.0.5 on 2026-05-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0005_alter_taskattempt_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattempt",
            name="terminal_container_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Имя контейнера терминала"
            ),
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="terminal_port",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Порт терминала"
            ),
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="terminal_url",
            field=models.URLField(blank=True, verbose_name="URL терминала"),
        ),
    ]
