# Generated by Django 6.0.5 on 2026-05-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0006_taskattempt_terminal_container_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="client_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email клиента"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="client_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Имя клиента"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                default="Medium", max_length=50, verbose_name="Приоритет"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="queue_name",
            field=models.CharField(
                default="ОТП Cloud L1", max_length=100, verbose_name="Очередь"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="ticket_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Тема тикета"
            ),
        ),
    ]
