# Generated by Django 6.0.5 on 2026-05-20 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0007_task_client_email_task_client_name_task_priority_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Queue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Очередь",
                "verbose_name_plural": "Очереди",
                "ordering": ["order"],
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["queue__order", "order"]},
        ),
        migrations.AlterField(
            model_name="task",
            name="client_email",
            field=models.EmailField(
                blank=True,
                default="client@example.ru",
                max_length=254,
                verbose_name="Email клиента",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="client_name",
            field=models.CharField(
                blank=True,
                default="Учебный клиент",
                max_length=255,
                verbose_name="Имя клиента",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="slug",
            field=models.SlugField(verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="task",
            name="ticket_title",
            field=models.CharField(
                blank=True,
                default="Обращение в службу поддержки",
                max_length=255,
                verbose_name="Тема тикета",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="queue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="sandbox.queue",
                verbose_name="Очередь",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("queue", "slug"), name="unique_task_slug_per_queue"
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("queue", "order"), name="unique_task_order_per_queue"
            ),
        ),
    ]
