# Generated by Django 6.0.5 on 2026-05-20 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0008_queue_alter_task_options_alter_task_client_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="required_level",
            field=models.CharField(
                choices=[
                    ("candidate", "Кандидат"),
                    ("l1", "L1"),
                    ("l2", "L2"),
                    ("admin", "Системный администратор"),
                ],
                default="candidate",
                max_length=32,
                verbose_name="Минимальный уровень",
            ),
        ),
        migrations.CreateModel(
            name="TraineeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("candidate", "Кандидат"),
                            ("l1", "L1"),
                            ("l2", "L2"),
                            ("admin", "Системный администратор"),
                        ],
                        default="candidate",
                        max_length=32,
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "is_mentor",
                    models.BooleanField(default=False, verbose_name="Наставник"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainee_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль стажера",
                "verbose_name_plural": "Профили стажеров",
            },
        ),
    ]
