# Generated by Django 6.0.5 on 2026-05-27 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0010_seed_candidate_and_l1_queues"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="queue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="sandbox.queue",
                verbose_name="Очередь",
            ),
        ),
    ]
