# Generated by Django 6.0.5 on 2026-05-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0011_alter_task_queue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="queue_name",
        ),
    ]
