# Generated by Django 6.0.5 on 2026-05-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0013_normalize_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Низкий"),
                    ("medium", "Средний"),
                    ("high", "Высокий"),
                    ("critical", "Критический"),
                ],
                default="medium",
                max_length=20,
                verbose_name="Приоритет",
            ),
        ),
    ]
