# Generated by Django 6.0.5 on 2026-05-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0014_alter_task_priority"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["queue__order", "order"],
                "verbose_name": "Задание",
                "verbose_name_plural": "Задания",
            },
        ),
    ]
