# Generated by Django 6.0.5 on 2026-05-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0015_alter_task_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="traineeprofile",
            name="is_mentor",
        ),
    ]
