# Generated by Django 6.0.5 on 2026-05-28 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0016_remove_traineeprofile_is_mentor"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("passed", "Пройдена"), ("failed", "Не пройдена")],
                        max_length=20,
                        verbose_name="Результат",
                    ),
                ),
                ("output", models.TextField(blank=True, verbose_name="Вывод проверки")),
                ("exit_code", models.IntegerField(verbose_name="Код выхода")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата проверки"
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_runs",
                        to="sandbox.taskattempt",
                        verbose_name="Попытка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запуск проверки",
                "verbose_name_plural": "Запуски проверок",
                "ordering": ["-created_at"],
            },
        ),
    ]
