# Generated by Django 6.0.5 on 2026-06-01 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0017_checkrun"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattempt",
            name="mentor_feedback",
            field=models.TextField(blank=True, verbose_name="Комментарий наставника"),
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="mentor_reviewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата проверки наставником"
            ),
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="mentor_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_attempts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Проверил наставник",
            ),
        ),
    ]
