# Generated by Django 6.0.5 on 2026-06-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0018_taskattempt_mentor_feedback_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattempt",
            name="mentor_decision",
            field=models.CharField(
                choices=[
                    ("not_reviewed", "Не проверено"),
                    ("approved", "Принято"),
                    ("needs_revision", "Нужна доработка"),
                ],
                default="not_reviewed",
                max_length=32,
                verbose_name="Решение наставника",
            ),
        ),
    ]
