# Generated by Django 6.0.5 on 2026-06-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0019_taskattempt_mentor_decision"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattempt",
            name="mentor_feedback_seen_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Комментарий наставника прочитан"
            ),
        ),
    ]
