# Generated by Django 6.0.5 on 2026-06-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0020_taskattempt_mentor_feedback_seen_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="requires_manual_review",
            field=models.BooleanField(
                default=False, verbose_name="Требует ручной проверки наставника"
            ),
        ),
    ]
