# Generated by Django 6.0.5 on 2026-06-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0021_task_requires_manual_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattempt",
            name="technical_passed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Техническая часть пройдена"
            ),
        ),
    ]
