# Generated by Django 6.0.5 on 2026-06-08 11:18

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0022_taskattempt_technical_passed_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskattempt",
            options={
                "ordering": [
                    "user__username",
                    "task__queue__order",
                    "task__order",
                    "-attempt_number",
                ],
                "verbose_name": "Попытка прохождения",
                "verbose_name_plural": "Попытки прохождения",
            },
        ),
        migrations.AlterUniqueTogether(
            name="taskattempt",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="attempt_number",
            field=models.PositiveIntegerField(default=1, verbose_name="Номер попытки"),
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Создана",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="is_current",
            field=models.BooleanField(default=True, verbose_name="Текущая попытка"),
        ),
        migrations.AddConstraint(
            model_name="taskattempt",
            constraint=models.UniqueConstraint(
                fields=("user", "task", "attempt_number"),
                name="unique_attempt_number_per_user_task",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("user", "task"),
                name="unique_current_attempt_per_user_task",
            ),
        ),
    ]
