# Generated by Django 6.0.5 on 2026-06-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0023_alter_taskattempt_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskattempt",
            name="terminal_url",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="URL терминала"
            ),
        ),
    ]
