# Generated by Django 6.0.5 on 2026-06-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0024_alter_taskattempt_terminal_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattempt",
            name="check_finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="check_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="check_status",
            field=models.CharField(
                choices=[
                    ("idle", "Не запускалась"),
                    ("running", "Выполняется"),
                    ("passed", "Пройдена"),
                    ("failed", "Не пройдена"),
                    ("error", "Ошибка"),
                ],
                default="idle",
                max_length=20,
            ),
        ),
    ]
