# Generated by Django 6.0.5 on 2026-07-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0025_taskattempt_check_finished_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattempt",
            name="environment_finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="environment_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="environment_status",
            field=models.CharField(
                choices=[
                    ("idle", "Не запущено"),
                    ("starting", "Запускается"),
                    ("ready", "Готово"),
                    ("restarting", "Перезапускается"),
                    ("error", "Ошибка"),
                ],
                default="idle",
                max_length=20,
            ),
        ),
    ]
