# Generated by Django 6.0.5 on 2026-07-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0026_taskattempt_environment_finished_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattempt",
            name="stuck_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Не зависала"),
                    ("environment", "Окружение"),
                    ("check", "Автопроверка"),
                ],
                default="",
                max_length=32,
                verbose_name="Причина зависания",
            ),
        ),
    ]
