# Generated by Django 6.0.5 on 2026-09-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0027_taskattempt_stuck_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="ai_review_context",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Контекст для AI-проверки"
            ),
        ),
    ]
