# Generated by Django 6.0.5 on 2026-09-21 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0028_task_ai_review_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_answer",
                    models.TextField(verbose_name="Проверенный ответ клиенту"),
                ),
                (
                    "task_context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Контекст задания на момент проверки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("running", "Выполняется"),
                            ("completed", "Завершена"),
                            ("error", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "checks",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Результаты проверки"
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Рекомендации"
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Полный ответ AI"
                    ),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=255, verbose_name="Модель"),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        default="v1", max_length=32, verbose_name="Версия промпта"
                    ),
                ),
                (
                    "input_tokens",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Входные токены"
                    ),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Выходные токены"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Ошибка AI"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Начата"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершена"
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_reviews",
                        to="sandbox.taskattempt",
                        verbose_name="Попытка",
                    ),
                ),
            ],
        ),
    ]
