# Generated by Django 6.0.5 on 2026-09-23 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0029_aireview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aireview',
            name='mentor_decision',
            field=models.CharField(blank=True, choices=[('approved', 'Принято'), ('needs_revision', 'Нужна доработка')], default='', max_length=20, verbose_name='Решение наставника'),
        ),
        migrations.AddField(
            model_name='aireview',
            name='mentor_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Проверено наставником'),
        ),
        migrations.AddField(
            model_name='aireview',
            name='mentor_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Проверил наставник'),
        ),
    ]
