# Generated by Django 6.0.5 on 2026-07-15 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TraineeStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("order", models.PositiveIntegerField()),
                ("min_days", models.PositiveIntegerField(default=1)),
                ("max_days", models.PositiveIntegerField(default=100)),
                ("progress_weight_percent", models.PositiveIntegerField(default=0)),
                ("color", models.CharField(default="#9CA3AF", max_length=7)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("teachbase", "Teachbase"),
                            ("sandbox_candidate", "Задания в ticket-sandbox"),
                            ("with_review", "В тикетах с проверками"),
                            ("optional_review", "Кнопка по желанию"),
                            ("no_review", "Без проверок"),
                            ("done", "Завершено"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "applies_to_new_hire",
                    models.BooleanField(
                        default=True, verbose_name="Актуален для внешнего найма"
                    ),
                ),
                (
                    "applies_to_internal_transfer",
                    models.BooleanField(
                        default=True, verbose_name="Актуален для внутреннего перехода"
                    ),
                ),
            ],
            options={
                "verbose_name": "Этап обучения",
                "verbose_name_plural": "Этапы обучения",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TraineeJourney",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("new_hire", "Новая адаптация"),
                            ("internal_transfer", "Внутренний переход"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "probation_start_date",
                    models.DateField(verbose_name="Дата старта ИС"),
                ),
                (
                    "stage_started_at",
                    models.DateField(verbose_name="Дата начала этапа"),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "manual_risk_override",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Низкий"),
                            ("medium", "Средний"),
                            ("high", "Высокий"),
                        ],
                        max_length=16,
                        verbose_name="Риск (ручной override)",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainee_journey",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="traineediary.traineestage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карточка стажёра",
                "verbose_name_plural": "Карточки стажёров",
            },
        ),
        migrations.CreateModel(
            name="StageHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateField()),
                ("ended_at", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_history",
                        to="traineediary.traineejourney",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="traineediary.traineestage",
                    ),
                ),
            ],
            options={
                "verbose_name": "История этапов",
                "verbose_name_plural": "История этапов",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="WeeklyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.PositiveIntegerField()),
                ("week_start_date", models.DateField(blank=True, null=True)),
                (
                    "speed_hours",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("quality_percent", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_metrics",
                        to="traineediary.traineejourney",
                    ),
                ),
            ],
            options={
                "verbose_name": "Недельная метрика",
                "verbose_name_plural": "Недельные метрики",
                "ordering": ["week_number"],
                "unique_together": {("journey", "week_number")},
            },
        ),
    ]
