# Generated by Django 6.0.5 on 2026-07-17 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traineediary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklymetric",
            name="quality_percent",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="weeklymetric",
            name="speed_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="weeklymetric",
            name="week_number",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklymetric",
            constraint=models.CheckConstraint(
                condition=models.Q(("week_number__gte", 1)),
                name="weekly_metric_week_number_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklymetric",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("speed_hours__isnull", True),
                    ("speed_hours__gte", 0),
                    _connector="OR",
                ),
                name="weekly_metric_speed_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklymetric",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quality_percent__isnull", True),
                    models.Q(
                        ("quality_percent__gte", 0), ("quality_percent__lte", 100)
                    ),
                    _connector="OR",
                ),
                name="weekly_metric_quality_between_0_100",
            ),
        ),
    ]
