# Generated by Django 6.0.5 on 2026-07-20 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traineediary", "0002_alter_weeklymetric_quality_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="traineejourney",
            name="fixed_quality_percent",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Зафиксированное качество",
            ),
        ),
        migrations.AddField(
            model_name="traineejourney",
            name="quality_fixed_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата фиксации качества"
            ),
        ),
    ]
