# Generated by Django 6.0.5 on 2026-07-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traineediary", "0003_traineejourney_fixed_quality_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklymetric",
            name="mentor_comment",
            field=models.TextField(blank=True, verbose_name="Итоги недели"),
        ),
        migrations.AddField(
            model_name="weeklymetric",
            name="next_week_goal",
            field=models.TextField(blank=True, verbose_name="Цель на следующую неделю"),
        ),
    ]
