# Generated by Django 6.0.5 on 2026-07-29 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traineediary", "0004_weeklymetric_mentor_comment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="traineejourney",
            name="completed_at",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Дата завершения испытательного срока",
            ),
        ),
        migrations.AddField(
            model_name="traineejourney",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Завершил испытательный срок",
            ),
        ),
        migrations.AddField(
            model_name="traineejourney",
            name="completion_comment",
            field=models.TextField(blank=True, verbose_name="Итоговый комментарий"),
        ),
        migrations.AddField(
            model_name="traineejourney",
            name="completion_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("success", "Испытательный срок успешно пройден"),
                    ("terminated", "Испытательный срок прекращён"),
                ],
                max_length=16,
                verbose_name="Результат испытательного срока",
            ),
        ),
    ]
